import { cars } from './data';

// PROTOTYPE ONLY. These eleven fictional listings supplement the five existing
// illustrative cars ONLY in the Orbit catalogue. Never publish as real inventory.
// Replace this module with confirmed stock before production. The local placeholder
// deliberately does not depict a make/model we cannot verify.
export const catalogIsDemo = true;
const image = '/catalog-placeholder.svg';
export const additionalDemoCars = [
  {
    id: 'demo-bmw-serie-1',
    brand: 'BMW',
    model: 'Série 1',
    line: '116d · Compacto para os seus dias.',
    year: 2020,
    km: 68400,
    fuel: 'Diesel',
    power: 116,
    price: 21900,
    category: 'Compacto',
    transmission: 'Manual',
    image,
    isDemo: true,
  },
  {
    id: 'demo-bmw-serie-1-118i',
    brand: 'BMW',
    model: 'Série 1',
    line: '118i · Uma nova rotina.',
    year: 2022,
    km: 32600,
    fuel: 'Gasolina',
    power: 136,
    price: 27900,
    category: 'Compacto',
    transmission: 'Automática',
    image,
    isDemo: true,
  },
  {
    id: 'demo-bmw-serie-2',
    brand: 'BMW',
    model: 'Série 2',
    line: '216d Active Tourer · Espaço para a família.',
    year: 2019,
    km: 81200,
    fuel: 'Diesel',
    power: 116,
    price: 19900,
    category: 'Familiar',
    transmission: 'Manual',
    image,
    isDemo: true,
  },
  {
    id: 'demo-renault-clio',
    brand: 'Renault',
    model: 'Clio',
    line: '1.0 TCe · Simples de escolher.',
    year: 2021,
    km: 45800,
    fuel: 'Gasolina',
    power: 90,
    price: 14900,
    category: 'Citadino',
    transmission: 'Manual',
    image,
    isDemo: true,
  },
  {
    id: 'demo-peugeot-208',
    brand: 'Peugeot',
    model: '208',
    line: '1.2 PureTech · À escala da cidade.',
    year: 2022,
    km: 29300,
    fuel: 'Gasolina',
    power: 100,
    price: 16900,
    category: 'Citadino',
    transmission: 'Manual',
    image,
    isDemo: true,
  },
  {
    id: 'demo-vw-golf',
    brand: 'Volkswagen',
    model: 'Golf',
    line: '1.6 TDI · Um companheiro de viagem.',
    year: 2018,
    km: 96500,
    fuel: 'Diesel',
    power: 115,
    price: 17400,
    category: 'Compacto',
    transmission: 'Manual',
    image,
    isDemo: true,
  },
  {
    id: 'demo-toyota-yaris',
    brand: 'Toyota',
    model: 'Yaris',
    line: '1.5 Hybrid · Para o dia a dia.',
    year: 2023,
    km: 18200,
    fuel: 'Híbrido',
    power: 116,
    price: 22900,
    category: 'Citadino',
    transmission: 'Automática',
    image,
    isDemo: true,
  },
  {
    id: 'demo-seat-leon',
    brand: 'SEAT',
    model: 'Leon',
    line: '1.0 TSI · Espaço para os seus planos.',
    year: 2020,
    km: 53700,
    fuel: 'Gasolina',
    power: 110,
    price: 18900,
    category: 'Compacto',
    transmission: 'Manual',
    image,
    isDemo: true,
  },
  {
    id: 'demo-skoda-octavia',
    brand: 'Škoda',
    model: 'Octavia',
    line: '2.0 TDI DSG · Mais espaço, mais possibilidades.',
    year: 2021,
    km: 72300,
    fuel: 'Diesel',
    power: 150,
    price: 24900,
    category: 'Familiar',
    transmission: 'Automática',
    image,
    isDemo: true,
  },
  {
    id: 'demo-dacia-sandero',
    brand: 'Dacia',
    model: 'Sandero',
    line: '1.0 ECO-G · O essencial para partir.',
    year: 2022,
    km: 41800,
    fuel: 'GPL',
    power: 100,
    price: 12900,
    category: 'Citadino',
    transmission: 'Manual',
    image,
    isDemo: true,
  },
  {
    id: 'demo-opel-corsa',
    brand: 'Opel',
    model: 'Corsa',
    line: '1.2 Edition · Ao seu ritmo.',
    year: 2020,
    km: 61400,
    fuel: 'Gasolina',
    power: 75,
    price: 12400,
    category: 'Citadino',
    transmission: 'Manual',
    image,
    isDemo: true,
  },
];
export const catalogCars = [...cars, ...additionalDemoCars];
export function transmissionFor(car: (typeof catalogCars)[number]) {
  // Preserve the original detail template's automatic gearbox for its five cars.
  return 'transmission' in car ? car.transmission : 'Automática';
}
